trainer_config:
  max_epochs: 100
  min_epochs: 10
  gpus: "0"

checkpoint_config:
  save_last: True

earlystop_config:

dataset: Gaussian2D
ood_dataset: AnomalousGaussian2D
seed: 1
batch_size: 128
data_shape: [2]

model_name: EnergyOOD
model_config:
  arch_name: fc
  arch_config:
    inp_dim: 2
    num_classes: 3
  learning_rate: 0.0001
  momentum: 0.5
  weight_decay: 0.
  m_in: -23
  m_out: -5
  score: "energy"
  checkpoint: "logs/CEBaseline/Gaussian2D/2020-12-23-12-14-56/epoch=58-step=530.ckpt"
  max_steps: 1500
