trainer_config:
  max_steps: 1_000_000
  max_epochs: 1_000_000
  val_check_interval: 10_000
  limit_val_batches: 2000
  limit_test_batches: 1.0
  gpus: 1
  benchmark: True

checkpoint_config:
  monitor: val/loss
  mode: min

earlystop_config:
  monitor: val/loss
  mode: min
  patience: 10

dataset: genomics
ood_dataset:
seed: 1
batch_size: 512
data_shape: [250]

model_name: NormalizingFlow
model_config:
  arch_name: seq_generator
  arch_config:
    input_size: 4
    hidden_size: 128
    num_classes: 4
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
