trainer_config:
  max_epochs: 10_000
  check_val_every_n_epoch: 100
  gpus: 1
  benchmark: True

checkpoint_config:
  monitor: val/loss
  mode: min

earlystop_config:
  monitor: val/loss
  mode: min
  patience: 10

test_ood_datasets:
  - segment-ood

dataset: segment
ood_dataset:
seed: 1
batch_size: 512
data_shape: [18]

model_name: CEBaseline
model_config:
  arch_name: fc
  arch_config:
    inp_dim: 18
    num_classes: 6
    hidden_dims: [100, 100, 100, 100, 100]
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
