seml:
  executable: uncertainty_est/train.py
  output_dir: slurm
  project_root_dir: ../../..

slurm:
  experiments_per_job: 5
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 5  # num cores
    time: 0-5:00     # max time, D-HH:MM
    exclude: gpu09

fixed:
  trainer_config:
    max_epochs: 5_000
    max_steps: 5_000
    gpus: 1
    limit_val_batches: 0
    benchmark: True

  checkpoint_config:
    monitor:
    save_last: True

  earlystop_config:

  log_dir: grid_search/segment
  output_folder: segment_mcmc

  dataset: &dataset segment
  ood_dataset: *dataset
  batch_size: 512
  data_shape: &data_shape
    - &data_dim 18

  test_ood_datasets:
    - segment-ood

  model_name: JEM
  model_config:
    arch_name: fc
    arch_config:
      inp_dim: *data_dim
      num_classes: 1
      hidden_dims: [100, 100, 100, 100, 100]

    learning_rate: 0.001
    momentum: 0.9
    weight_decay: 0.0
    smoothing: 0.0
    sgld_lr: 1.0
    sgld_std: 0.01
    sgld_steps: 100
    pyxce: 0.0
    pxsgld: 1.0
    pxysgld: 0.0
    buffer_size: 9999
    reinit_freq: 0.05
    data_shape: *data_shape
    uncond: True
    sgld_batch_size: 512
    class_cond_p_x_sample: False
    n_classes: 1
    warmup_steps: 2500
    energy_reg_weight: 0.0
    energy_reg_type: 2
    entropy_reg_weight: 0.0
    lr_step_size: 1000

grid:
  seed:
    type: choice
    options:
     - 2525
     - 2123
     - 293993
     - 2324234
     - 6566634
