trainer_config:
  max_steps: 100_000
  max_epochs: 100_000
  gpus: 1
  limit_val_batches: 1
  benchmark: True

checkpoint_config:
  monitor:
  save_last: True

earlystop_config:

dataset: Gaussian2D
# Use second dataset
ood_dataset: Gaussian2D
seed: 1
batch_size: 128
data_shape: &data_shape [2]

model_name: JEM
model_config:
  arch_name: fc
  arch_config:
    inp_dim: 2
    num_classes: 1
    hidden_dims: [100, 100, 100, 100, 100]
    batch_norm: False
    bias: True
    slope: 0.2

  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0
  smoothing: 0.0
  sgld_lr: 1.
  sgld_std: 0.1
  sgld_steps: 100
  pyxce: 0.0
  pxsgld: 1.0
  pxysgld: 0.0
  buffer_size: 9999
  reinit_freq: 0.05
  data_shape: *data_shape
  sgld_batch_size: 128
  class_cond_p_x_sample: False
  n_classes: 1
  warmup_steps: 100
  kl_term: 1.0
  entropy_term: 0.3
  annealed_sgld: True
  vis_every: 1000
  is_toy_dataset: True
  lr_step_size: 1000
