trainer_config:
  max_steps: 100_000
  max_epochs: 100_000
  gpus: 1

checkpoint_config:
  monitor:
  save_last: True

earlystop_config:

dataset: Gaussian2D
ood_dataset:
seed: 1
batch_size: 1024
data_shape: [2]

model_name: FlowCE
model_config:
  arch_name: fc
  arch_config:
    inp_dim: 2
    num_classes: 1
    hidden_dims: [100, 100]
    batch_norm: False
    bias: True
    slope: 0.2

  flow_arch_name: normalizing_flow
  flow_arch_config:
    flow_type: radial_flow
    dim: 2
    flow_length: 20

  flow_learning_rate: 0.001
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0
  is_toy_dataset: True
  toy_dataset_dim: 2
