trainer_config:
  max_steps: 100_000
  max_epochs: 100_000
  check_val_every_n_epoch: 10
  terminate_on_nan: True
  gpus: 1

checkpoint_config:
  monitor:
  save_last: True

earlystop_config:

dataset: Gaussian2D
ood_dataset:
seed: 1
batch_size: 32
data_shape: [2]

model_name: FlowCE
model_config:
  arch_name: fc
  arch_config:
    inp_dim: 2
    num_classes: 1
    hidden_dims: [100, 100, 100, 100, 100]
    batch_norm: False
    bias: True
    slope: 0.2

  flow_arch_name: normalizing_flow
  flow_arch_config:
    flow_type: affine_coupling
    dim: 2
    flow_length: 10

  flow_learning_rate: 0.0001
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
  is_toy_dataset: True
  toy_dataset_dim: 2
