trainer_config:
  max_steps: 100_000
  max_epochs: 100_000
  gpus: 1

checkpoint_config:
  monitor: val/loss
  mode: min

earlystop_config:
  monitor: val/loss
  mode: min
  patience: 10

dataset: Gaussian2D
ood_dataset:
seed: 1
batch_size: 1024
data_shape: [2]

model_name: NormalizingFlow
model_config:
  arch_name: normalizing_flow
  arch_config:
    flow_type: radial_flow
    dim: 2
    flow_length: 20
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0
  vis_every: 10
