trainer_config:
  max_steps: 10000
  gpus: "0"

checkpoint_config:
  monitor: val_loss
  mode: min

earlystop_config:
  monitor: val_loss
  mode: min
  patience: 10

dataset: Gaussian2D
ood_dataset:
seed: 1
batch_size: 1024
data_shape: [2]

model_name: NormalizingFlow
model_config:
  density_type: radial_flow
  latent_dim: 2
  n_density: 20
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0
