trainer_config:
  max_epochs: 500
  gpus: "0"
  check_val_every_n_epoch: 10
  terminate_on_nan: True

checkpoint_config:
  monitor:

earlystop_config:

dataset: Gaussian2D
ood_dataset:
seed: 1
batch_size: 128
data_shape: [2]

model_name: RegularizedEBM
model_config:
  arch_name: fc
  arch_config:
    inp_dim: 2
    num_classes: 3
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
  vis_every: 1
