trainer_config:
  max_steps: 100_000
  max_epochs: 100_000
  gpus: 1

checkpoint_config:
  monitor: val/loss
  mode: min

earlystop_config:

dataset: Gaussian2D
ood_dataset:
seed: 1
batch_size: 1024
data_shape: [2]

model_name: VAE
model_config:
  z_dim: &z_dim 2
  encoder_arch_name: fc
  encoder_arch_config:
    inp_dim: 2
    num_classes: *z_dim
  decoder_arch_name: fc
  decoder_arch_config:
    inp_dim: *z_dim
    num_classes: 2
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  vis_every: 1
