# @package fixed

checkpoint_config:
  monitor: val/loss
  mode: min

earlystop_config:
  monitor: val/loss
  mode: min
  patience: 10

ood_dataset:

model_name: NormalizingFlow
model_config:
  arch_name: normalizing_flow
  arch_config:
    flow_type: radial_flow
    dim: ${fixed.data_shape.0}
    flow_length: 20
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0
