# @package fixed

batch_size: 512

earlystop_config:
  monitor: val/acc
  mode: max
  patience: 10

model_name: CEBaseline
model_config:
  arch_name: seq_classifier
  arch_config:
    in_channels: ${fixed.num_cat}
    num_filters: 128
    fc_hidden_size: 1000
    num_classes: 10
    kernel_size: 20
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
