# @package fixed

trainer_config:
  max_steps: 100_000
  max_epochs: 100_000
  limit_val_batches: 1
  val_check_interval: 10_000
  limit_test_batches: 10_000

checkpoint_config:
  save_last: True

earlystop_config:

ood_dataset: ${fixed.dataset}

model_name: DiscreteMCMC
model_config:
  num_cat: ${fixed.num_cat}

  arch_name: seq_classifier
  arch_config:
    in_channels: ${fixed.num_cat}
    num_filters: 128
    fc_hidden_size: 1000
    num_classes: 1
    kernel_size: 20

  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
  smoothing: 0.0
  sgld_steps: 40
  pyxce: 0.0
  pxsgld: 1.0
  pxysgld: 0.0
  buffer_size: 9999
  reinit_freq: 0.0
  data_shape: ${fixed.data_shape}
  sgld_batch_size: ${fixed.batch_size}
  class_cond_p_x_sample: False
  n_classes: 1
  warmup_steps: 2500
  entropy_reg_weight: 0.0
  lr_step_size: 1000
