# @package fixed

batch_size: 512

earlystop_config:

ood_dataset: ${fixed.dataset}

model_name: DiscreteMCMC
model_config:
  num_cat: ${fixed.num_cat}

  arch_name: seq_classifier
  arch_config:
    in_channels: ${fixed.num_cat}
    num_filters: 128
    fc_hidden_size: 1000
    num_classes: ${fixed.num_classes}
    kernel_size: 20

  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
  smoothing: 0.0
  sgld_steps: 40
  pyxce: 1.0
  pxsgld: 1.0
  pxysgld: 0.0
  buffer_size: 9999
  reinit_freq: 0.0
  data_shape: ${fixed.data_shape}
  sgld_batch_size: 512
  class_cond_p_x_sample: True
  n_classes: ${fixed.num_classes}
  warmup_steps: 2500
  entropy_reg_weight: 0.0001
  lr_step_size: 1000
