# @package fixed

checkpoint_config:
  monitor: val/loss
  mode: min

earlystop_config:
  monitor: val/loss
  mode: min
  patience: 10

batch_size: 512

model_name: NormalizingFlow
model_config:
  arch_name: seq_generative_model
  arch_config:
    input_size: ${fixed.num_cat}
    hidden_size: 128
    num_classes: ${fixed.num_classes}
  learning_rate: 0.005
  momentum: 0.9
  weight_decay: 0.0005
