trainer_config:
  max_epochs: 500
  gpus: "0"

checkpoint_config:
  monitor: val_acc
  mode: max

earlystop_config:
  monitor: val_acc
  mode: max
  patience: 10

dataset: cifar10
ood_dataset: cifar100
seed: 1
batch_size: 128
data_shape: [3, 32, 32]

model_name: PriorNet
model_config:
  arch_name: wrn
  arch_config:
    depth: 28
    num_classes: 10
    widen_factor: 10
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
  target_concentration: 100.0
  concentration: 1.0
  gamma: 1.
  reverse_kl: True
  alpha_fix: True
