trainer_config:
  max_epochs: 40
  gpus: 1
  benchmark: True

checkpoint_config:
  monitor: "val/loss"
  mode: min
  save_last: True

earlystop_config:
  monitor: "val/loss"
  mode: min
  patience: 10

test_ood_datasets:
  - kmnist
  - fashionmnist
  - gaussian_noise
  - uniform_noise

dataset: mnist
# Use second dataset
ood_dataset:
seed: 1
batch_size: 32
data_shape:
  - 32
  - 32
  - &n_channels 1

model_name: RealNVP
model_config:
  num_scales: 2
  in_channels: *n_channels
  mid_channels: 32
  num_blocks: 4
  num_classes: 10
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.00005
