trainer_config:
  max_epochs: 500
  gpus: "0"

checkpoint_config:
  monitor: val_loss
  mode: min

earlystop_config:
  monitor: val_loss
  mode: min
  patience: 10

dataset: cifar10
# Use second dataset
ood_dataset: cifar10
seed: 1
batch_size: 40
data_shape: [3, 32, 32]

model_name: VERA
model_config:
  arch_name: wideresnet
  arch_config:
    depth: 28
    num_classes: 10
    widen_factor: 10
  learning_rate: 0.0005
  momentum: 0.0
  weight_decay: 0.0
  gen_learning_rate: 0.00006
  ebm_iters: 1
  generator_iters: 1
  entropy_weight: 0.0001
  generator_type: vera
  generator_arch_name: resnetgenerator
  generator_arch_config:
    unit_interval: False
    feats: 128
  generator_config:
    noise_dim: 128
    post_lr: 0.00003
    init_post_logsigma: 0.1
  min_sigma: 0.01
  max_sigma: 0.3
  p_control: 0.0
  n_control: 0.0
  pg_control: 0.1
  clf_ent_weight: 0.0
  ebm_type: jem
  clf_weight: 100.0
  warmup_iters: 2500
  no_g_batch_norm: False
  batch_size: 40
  lr_decay: 0.3
  lr_decay_epochs: [150, 175]
