trainer_config:
  max_epochs: 40
  gpus: 1
  benchmark: True

checkpoint_config:
  monitor: val/acc
  mode: max
  save_last: True

earlystop_config:

test_ood_datasets:
  - kmnist
  - fashionmnist
  - gaussian_noise
  - uniform_noise

dataset: &dataset mnist
ood_dataset: *dataset
seed: 1
batch_size: &batch_size 32
data_shape:
  - 32
  - 32
  - &n_channels 1

model_name: VERA
model_config:
  n_classes: &n_classes 10
  arch_name: wrn
  arch_config:
    depth: 28
    num_classes: *n_classes
    widen_factor: 10
    input_channels: *n_channels
    strides: [1, 2, 2]
  learning_rate: 0.00003
  beta1: 0.0
  beta2: 0.9
  weight_decay: 0.0
  gen_learning_rate: 0.00006
  ebm_iters: 1
  generator_iters: 1
  entropy_weight: 0.0001
  generator_type: vera
  generator_arch_name: resnetgenerator
  generator_arch_config:
    unit_interval: False
    feats: 128
    out_channels: *n_channels
  generator_config:
    noise_dim: 128
    post_lr: 0.00003
    init_post_logsigma: 0.1
  min_sigma: 0.01
  max_sigma: 0.3
  p_control: 0.0
  n_control: 0.0
  pg_control: 0.1
  clf_ent_weight: 0.0
  ebm_type: jem
  clf_weight: 100.0
  warmup_steps: 2500
  no_g_batch_norm: False
  batch_size: *batch_size
  lr_decay: 0.3
  lr_decay_epochs: [30, 35]
