# @package fixed

dataset: cifar10
num_classes: 10
batch_size: 32
data_shape: [32, 32, 3]

test_ood_datasets:
  - lsun
  - textures
  - cifar100
  - svhn
  - celeb-a
  - uniform_noise
  - gaussian_noise
  - constant
