# @package _global_

slurm:
  experiments_per_job: 5
  sbatch_options:
    time: 0-10:00
    mem: 32G

fixed:
  dataset: genomics_embedded
  batch_size: 512
  data_shape:
    - 128
  num_classes: 10

  checkpoint_config:
    monitor: val/ood
    mode: max

  test_ood_datasets:
    - genomics-ood_embedded
    - genomics-noise_embedded

  trainer_config:
    max_epochs: 50_000
    max_steps: 50_000

  model_config:
    ood_val_datasets:
      - genomics-ood_embedded
