# @package _global_

slurm:
  experiments_per_job: 1
  sbatch_options:
    time: 0-30:00
    mem: 32G

fixed:
  dataset: genomics
  data_shape: [250]
  num_cat: 4
  num_classes: 10

  test_ood_datasets:
    - genomics-ood
    - genomics-noise

  model_config:
    ood_val_datasets:
      - genomics-ood

  checkpoint_config:
    monitor: val/ood
    mode: max
    save_last: True

  trainer_config:
    max_steps: 100_000
    max_epochs: 100_000
    limit_val_batches: 1000
    val_check_interval: 10_000
    limit_test_batches: 10_000
