# @package _global_

slurm:
  experiments_per_job: 1
  sbatch_options:
    time: 0-30:00
    mem: 32G

fixed:
  dataset: genomics
  data_shape: [250]
  num_cat: 4
  num_classes: 10

  test_ood_datasets:
    - genomics-ood
    - genomics-noise
