# @package _global_

slurm:
  experiments_per_job: 5
  sbatch_options:
    time: 0-05:00

fixed:
  dataset: sensorless
  num_classes: 9
  batch_size: 512
  data_shape: [48]

  test_ood_datasets:
    - sensorless-ood
    - uniform_noise
    - gaussian_noise
    - constant

  checkpoint_config:
    monitor: val/ood
    mode: max
    save_last: True

  trainer_config:
    max_epochs: 10_000
    max_steps: 10_000
    check_val_every_n_epoch: 10

  model_config:
    ood_val_datasets:
      - sensorless-ood
