trainer_config:
  max_epochs: 40
  gpus: 1
  limit_val_batches: 0
  benchmark: True

checkpoint_config:
  monitor:
  save_last: True

earlystop_config:

test_ood_datasets:
  - fashionmnist
  - kmnist
  - gaussian_noise
  - uniform_noise

dataset: &dataset mnist
# Use second dataset
ood_dataset: *dataset
seed: 1
sigma: 0.03
batch_size: 32
data_shape:
  - 32
  - 32
  - &n_channels 1

model_name: JEM
model_config:
  n_classes: &n_classes 1
  arch_name: wrn
  arch_config:
    depth: 28
    num_classes: *n_classes
    widen_factor: 10
    input_channels: *n_channels

  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
  smoothing: 0.0
  sgld_lr: 0.01
  sgld_std: 0.1
  sgld_steps: 100
  pyxce: 0.0
  pxsgld: 1.0
  pxysgld: 0.0
  buffer_size: 9999
  reinit_freq: 0.05
  data_shape: [*n_channels, 32, 32]
  uncond: True
  sgld_batch_size: 32
  class_cond_p_x_sample: False
  warmup_steps: 2500
  energy_reg_weight: 0.0
  energy_reg_type: 2
  entropy_reg_weight: 0.0
  vis_every: -1
  is_toy_dataset: False
  lr_step_size: 30
