trainer_config:
  max_steps: 100_000
  max_epochs: 100_000
  gpus: "0"

checkpoint_config:
  monitor: val/loss
  mode: min

earlystop_config:
  monitor: val/loss
  mode: min
  patience: 10

dataset: mnist
ood_dataset:
seed: 1
batch_size: 128
data_shape: &data_shape [32, 32, 1]

model_name: IResNet
model_config:
  arch_name: iresnet_conv
  arch_config:
    in_shape: [1, 32, 32]
    n_blocks: [4, 4, 4]
    n_strides: [1, 2, 2]
    n_channels: [16, 64, 256]
    init_ds: 2
    density_estimation: True
    inj_pad: 0
    coeff: 0.9
    n_trace_samples: 1
    n_series_terms: 5
    n_power_iter: 5
    actnorm: True
    learn_prior: False
    nonlin: relu

  warmup_steps: 2500
  learning_rate: 0.003
  momentum: 0.9
  weight_decay: 0.0
  vis_every: -1
