trainer_config:
  max_epochs: 500
  gpus: 1

checkpoint_config:
  monitor:
  save_last: True

earlystop_config:

dataset: MNIST
ood_dataset:
seed: 1
batch_size: 128
data_shape:
  - 28
  - 28
  - &n_channels 1

model_name: NCE
model_config:
  arch_name: wrn
  arch_config:
    depth: 28
    num_classes: 1
    widen_factor: 10
    input_channels: *n_channels

  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
  noise_distribution: gaussian
  noise_distribution_kwargs:
    loc: 0.0
    scale: 0.5
