trainer_config:
  max_epochs: 200
  gpus: 1
  benchmark: True

checkpoint_config:
  monitor: val/loss
  mode: min

earlystop_config:
  monitor: val/loss
  mode: min

test_ood_datasets:
  - fashionmnist
  - kmnist
  - gaussian_noise
  - uniform_noise

dataset: mnist
ood_dataset:
seed: 1
batch_size: 64
data_shape:
  - 32
  - 32
  - &n_channels 1

model_name: VAE
model_config:
  z_dim: &z_dim 32
  encoder_arch_name: wrn
  encoder_arch_config:
    depth: 28
    num_classes: *z_dim
    widen_factor: 10
    input_channels: *n_channels
  decoder_arch_name: resnetgenerator
  decoder_arch_config:
    unit_interval:
    feats: *z_dim
    out_channels: *n_channels
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
  vis_every: 1
