trainer_config:
  max_epochs: 200
  gpus: "0"

arch_name: vgg16
arch_config:
  pretrained: False
  num_classes: 10

lr: 1e-3
momentum: 0.9
weight_decay: 0.0005
dataset: cifar10
seed: 1
batch_size: 128
monitor: val_loss
