seml:
  executable: uncertainty_est/models/ce_baseline.py
  name: ce_baseline
  output_dir: slurm
  project_root_dir: ..

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 8G          # memory
    cpus-per-task: 1  # num cores
    time: 0-08:00     # max time, D-HH:MM

###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  trainer_config:
    max_epochs: 500

  model_config:
    name: wrn
    depth: 28
    num_classes: 10
    widen_factor: 2
  
  lr: 0.0001
  dataset: cifar10
  seed: 1
  batch_size: 128
  monitor: val_ac
