trainer_config:
  max_epochs: 10
  min_epochs: 10
  gpus: "0"

arch_name: wrn
arch_config:
  depth: 28
  num_classes: 10
  widen_factor: 10

lr: 0.0001
momentum: 0.5
weight_decay: 0.
dataset: cifar10
seed: 1
batch_size: 128
ood_dataset: cifar100
monitor: val_loss
m_in: -23
m_out: -5
score: "energy"
checkpoint: "logs/wrn_cifar10_baseline/epoch=17.ckpt"