trainer_config:
  max_epochs: 500
  gpus: "0"

arch_name: wrn
arch_config:
  depth: 28
  num_classes: 10
  widen_factor: 10

lr: 1e-4
momentum: 0.9
weight_decay: 0.0
dataset: cifar10
ood_dataset: cifar100
seed: 1
batch_size: 128
monitor: val_acc
target_concentration: 100.0
concentration: 1.0
gamma: 1.
reverse_kl: True
alpha_fix: True

