seml:
  executable: uncertainty_est/train.py
  name: vera_postnet_gaussians
  output_dir: slurm
  project_root_dir: ..

slurm:
  experiments_per_job: 5
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 8G          # memory
    cpus-per-task: 5  # num cores
    time: 0-08:00     # max time, D-HH:MM

###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  trainer_config:
    max_steps: &steps 100_000
    max_epochs: *steps
    gpus: 1
    check_val_every_n_epoch: 10

  checkpoint_config:
    monitor:
    save_last: True

  earlystop_config:

  num_workers: 0
  log_dir: grid_search/vera_postnet_gaussians
  dataset: &dataset Gaussian2D
  # Use second dataset
  ood_dataset: *dataset
  seed: 1
  batch_size: 128
  data_shape: [2]

  model_name: VERAPosteriorNet
  model_config:
    arch_name: fc
    arch_config:
      inp_dim: 2
      num_classes: 3
      hidden_dims: [100, 100]
      batch_norm: False
      bias: True
      slope: 0.2

    # learning_rate: 0.0001
    beta1: 0.0
    beta2: 0.9
    weight_decay: 0.0
    n_classes: 3
    uncond: False
    # gen_learning_rate: 0.001
    ebm_iters: 1
    generator_iters: 1
    entropy_weight: 1.0

    generator_type: vera
    generator_arch_name: fc
    generator_arch_config:
      inp_dim: 2
      num_classes: 2
      hidden_dims: [100, 100]
      activation: relu
      batch_norm: True
      bias: False
    generator_config:
      noise_dim: 2
      post_lr: 0.001
      init_post_logsigma: 0.001

    min_sigma: 0.01
    max_sigma: 0.3
    p_control: 0.0
    n_control: 0.0
    pg_control: 0.1
    clf_ent_weight: 0.0
    ebm_type: jem
    # clf_weight: 1.0
    warmup_steps: 2500
    no_g_batch_norm: False
    batch_size: 128
    lr_decay: 1.0
    lr_decay_epochs: []
    vis_every: 1
    alpha_fix: True
    # entropy_reg: 0.0
    is_toy_dataset: True
    alpha_0_control: 0.0

grid:
  model_config:
    type: parameter_collection
    params:
      learning_rate:
        type: loguniform
        min: 1e-5
        max: 1e-2
        num: 4
      gen_learning_rate:
        type: loguniform
        min: 1e-5
        max: 1e-2
        num: 4
      entropy_reg:
        type: choice
        options:
          - 0.0
          - 0.0001
          - 1.0
      clf_weight:
        type: choice
        options:
          - 0.1
          - 1.0
          - 10.0
