trainer_config:
  max_epochs: 500
  gpus: 1
  benchmark: True

checkpoint_config:
  monitor: val_loss
  mode: min

earlystop_config:
  monitor: val_loss
  mode: min
  patience: 10

dataset: genomics_embedded
ood_dataset:
seed: 1
batch_size: 512
data_shape:
  - &data_dim 128

model_name: CEBaseline
model_config:
  arch_name: fc
  arch_config:
    inp_dim: *data_dim
    num_classes: 10
    hidden_dims: [100, 100, 100, 100, 100]
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0005
