trainer_config:
  max_epochs: 20
  gpus: 1

checkpoint_config:
  save_last: True

earlystop_config:

dataset: &dataset fashionmnist
ood_dataset: *dataset
seed: 1
sigma: 0.1
batch_size: &batch_size 32
data_shape: &data_shape
  - 32
  - 32
  - &n_channels 1

model_name: JEM
model_config:
  n_classes: &n_classes 1
  arch_name: wrn
  arch_config:
    depth: 10
    num_classes: *n_classes
    widen_factor: 2
    input_channels: *n_channels
    strides: [1, 2, 2]
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
  smoothing: 0.0
  sgld_lr: 1.
  sgld_std: 0.01
  sgld_steps: 100
  pyxce: 0.0
  pxsgld: 1.0
  pxysgld: 0.0
  buffer_size: 10000
  reinit_freq: 0.05
  data_shape: [1, 32, 32]
  uncond: True
  sgld_batch_size: 128
  class_cond_p_x_sample: False
  energy_reg_weight: 0.0
  energy_reg_type: 2
  entropy_reg_weight: 0.0
